export const runtime = 'nodejs';

function createPdfBuffer() {
  const content = `BT
/F1 24 Tf
72 770 Td
(Mohammad Kaif Ali) Tj
0 -34 Td
/F1 14 Tf
(Aspiring Data Analyst) Tj
0 -38 Td
/F1 11 Tf
(Python | SQL | Excel | Power BI | Pandas | NumPy | Git | GitHub) Tj
0 -30 Td
(Portfolio resume generated by the site for convenient download.) Tj
ET`;

  const header = '%PDF-1.4\n';
  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj\n',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n',
    `5 0 obj << /Length ${content.length} >> stream\n${content}\nendstream endobj\n`
  ];

  let offset = Buffer.byteLength(header, 'utf8');
  const offsets = ['0000000000 65535 f \n'];
  const bodyChunks = [header];
  const body = objects
    .map((object) => {
      const current = offset;
      offsets.push(`${String(current).padStart(10, '0')} 00000 n \n`);
      offset += Buffer.byteLength(object, 'utf8');
      bodyChunks.push(object);
      return object;
    })
    .join('');

  const pdfBody = bodyChunks.join('');
  const xrefStart = Buffer.byteLength(pdfBody, 'utf8');
  const xref = `xref\n0 6\n${offsets.join('')}trailer << /Size 6 /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return Buffer.from(pdfBody + xref, 'utf8');
}

export async function GET() {
  const pdf = createPdfBuffer();

  return new Response(pdf, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename="Mohammad-Kaif-Ali-Resume.pdf"',
      'Content-Length': pdf.byteLength.toString()
    }
  });
}